alias myip='echo $(wget -qO - https://api.ipify.org)'
alias localip="ifconfig | sed -En 's/127.0.0.1//;s/.*inet (addr:)?(([0-9]*\.){3}[0-9]*).*/\2/p'"
alias attrib='chmod'
alias del='rm'
alias list='ls -la'
alias tasklist='ps -uxa | less'
alias cls='clear'
alias lshidden='ls -d .* --color=auto'
alias mount='mount |column -t'
alias ping='ping -c 4'
alias listenports='netstat -tulanp | grep LISTEN'
alias allports='netstat -tulanp'
alias meminfo='free -m -l -t'
alias psmem='ps auxf | sort -nr -k 4'
alias psmem10='ps auxf | sort -nr -k 4 | head -10'
alias pscpu='ps auxf | sort -nr -k 3'
alias pscpu10='ps auxf | sort -nr -k 3 | head -10'
alias cpuinfo='lscpu'
alias bashreload="source ~/.bashrc && echo Bash config reloaded"
alias diskusage='df -h'
alias cmdusage='history | awk '\''{CMD[$2]++;count++;}END { for (a in CMD)print CMD[a] " " CMD[a]/count*100 "% " a;}'\'' | grep -v "./" | column -c3 -s " " -t | sort -nr | nl |  head -n10'
alias upgrade_kali='apt-get update && apt-get upgrade'
alias speedtest='wget -O /dev/null http://ftp.ntua.gr/pub/linux/debian-cd/current-live/amd64/iso-hybrid/debian-live-9.4.0-amd64-cinnamon.iso'
alias clipdir='pwd | xclip'
alias back='cd $OLDPWD'
alias now='date '\''+%A %d %B %Y - %T'\'''
alias playstewie='mpsyt playurl https://www.youtube.com/watch?v=rdHZG7XbpBc'
alias rickroll='mpsyt playurl https://www.youtube.com/watch?v=XOP10LM0c-A'
